// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgRbkC_PuehceDn4tRUgjmJ71-B1nI5A',
    appId: '1:546979448016:web:0149820baa456645f38ad5',
    messagingSenderId: '546979448016',
    projectId: 'to-do-app-3a7e4',
    authDomain: 'to-do-app-3a7e4.firebaseapp.com',
    storageBucket: 'to-do-app-3a7e4.firebasestorage.app',
    measurementId: 'G-RBYL2X0CWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXTgzbZTBrTItIRLsNzQae12MKGk4CLcM',
    appId: '1:546979448016:android:69e9f2db92747e48f38ad5',
    messagingSenderId: '546979448016',
    projectId: 'to-do-app-3a7e4',
    storageBucket: 'to-do-app-3a7e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_oVdpKVXNWrrU2ZKN8KtaWW2jxzfyUFQ',
    appId: '1:546979448016:ios:f5bfbac3f30a1100f38ad5',
    messagingSenderId: '546979448016',
    projectId: 'to-do-app-3a7e4',
    storageBucket: 'to-do-app-3a7e4.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_oVdpKVXNWrrU2ZKN8KtaWW2jxzfyUFQ',
    appId: '1:546979448016:ios:f5bfbac3f30a1100f38ad5',
    messagingSenderId: '546979448016',
    projectId: 'to-do-app-3a7e4',
    storageBucket: 'to-do-app-3a7e4.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArgRbkC_PuehceDn4tRUgjmJ71-B1nI5A',
    appId: '1:546979448016:web:ab3557381362d7c2f38ad5',
    messagingSenderId: '546979448016',
    projectId: 'to-do-app-3a7e4',
    authDomain: 'to-do-app-3a7e4.firebaseapp.com',
    storageBucket: 'to-do-app-3a7e4.firebasestorage.app',
    measurementId: 'G-5GFG15BR32',
  );
}
